Домашнее задание 10 спринт
ViAKan/Playlist_Maker pull request #3
Opened 2024-05-03 18:01 UTC by ViAKan

Жду проверки!

2024-05-04 02:20 UTC, DmitrijEgorow commented
Согласно дизайну в тёмной теме курсор должен быть синего цвета

<img width="560" alt="Screenshot 2024-05-04 at 09 16 37" src="https://github.com/ViAKan/Playlist_Maker/assets/36837067/9becc4d4-8031-4c1b-98a2-9b94d206c9c4">

2024-05-04 02:20 UTC, DmitrijEgorow commented
Стоит обрезать автора композиции, но при любом раскладе оставлять длительность композиции
![Screenshot_20240504_091537](https://github.com/ViAKan/Playlist_Maker/assets/36837067/53764154-a0c2-441f-9b23-9d774ed44fab)

2024-05-04 02:25 UTC, DmitrijEgorow requested changes

2024-05-04 02:25 UTC, DmitrijEgorow commented on app/src/main/java/com/example/playlistmaker/TrackAdapter.kt
> +    private val tracks: ArrayList<Track>
```suggestion
    private val tracks: List<Track>
```

2024-05-04 02:25 UTC, DmitrijEgorow commented on app/src/main/res/drawable/placehold.png
Не стоит использовать растровые изображения в таких случаях, на 4k телефонах выглядит некрасиво

<img width="1100" alt="Screenshot 2024-05-04 at 09 17 54" src="https://github.com/ViAKan/Playlist_Maker/assets/36837067/819c314f-6d75-4dd7-bffb-6e3bc591b0cb">

2024-05-04 02:25 UTC, DmitrijEgorow commented on app/src/main/res/layout/track_view.xml
> +
Много лишних пустых строчек

2024-05-05 13:24 UTC, ViAKan commented
Поправила замечания, жду проверки!

2024-05-06 10:41 UTC, DmitrijEgorow commented
> ```
> Стоит обрезать автора композиции, но при любом раскладе оставлять длительность композиции; и название композиции я бы сделал макс в одну строчку, выглядит не совсем красиво
> ```
> 
> ![Screenshot_20240504_091537](https://private-user-images.githubusercontent.com/36837067/327911970-53764154-a0c2-441f-9b23-9d774ed44fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTIzNTcsIm5iZiI6MTcxNDk5MjA1NywicGF0aCI6Ii8zNjgzNzA2Ny8zMjc5MTE5NzAtNTM3NjQxNTQtYTBjMi00NDFmLTliMjMtOWQ3NzRlZDQ0ZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEwNDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNTk2Y2E3ZTZjMGIwZGEyOWMxOTRmYWFjMzRiZjEyMGM4ZWU3MWIwMjFlZjZmZTdlYTMzYmU5ODBkNWJiMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5JrfwCuMZ63-nrRqlc8h3oycgwC5z4pXHMs6Ef9zVD4)

Актуально

2024-05-06 10:43 UTC, DmitrijEgorow commented
![Screenshot_20240506_173639](https://github.com/ViAKan/Playlist_Maker/assets/36837067/2c8c8080-4756-4308-bf5b-ffb2bd0f682e)

2024-05-06 10:44 UTC, DmitrijEgorow commented
Зачем название композиции обрезается на половине экрана?
![Screenshot_20240506_173916](https://github.com/ViAKan/Playlist_Maker/assets/36837067/7c580090-22d9-4edc-bd88-5ebba33c1610)

2024-05-06 15:09 UTC, ViAKan commented
Постаралась поправить, как смогла. У меня еще такой вопрос: где вы берете такие маленькие экранчики для эмуляции, я в Андроид Студио не смогла найти такие узкие?

2024-05-06 17:04 UTC, DmitrijEgorow commented
В Параметрах разработчика можно настроить минимальную ширину экрана
![Screenshot_20240507_000250](https://github.com/ViAKan/Playlist_Maker/assets/36837067/e3729872-8e6e-4164-b322-37875762a85f)
И в этом разделе находится много полезных настроек для отладки

2024-05-06 17:06 UTC, DmitrijEgorow commented
Можно настроить размер шрифта побольше и открыть в режиме всплывающего окна (тогда можно менять размеры довольно гибко)

https://github.com/ViAKan/Playlist_Maker/assets/36837067/88b11de5-0d05-4660-86ae-6e36ac4b2aaa

2024-05-23 19:58 UTC, merged